// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vision.proto
#ifndef GRPC_vision_2eproto__INCLUDED
#define GRPC_vision_2eproto__INCLUDED

#include "vision.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class Vision final {
 public:
  static constexpr char const* service_full_name() {
    return "Vision";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::Request>> FrameStream(::grpc::ClientContext* context, ::Response* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::Request>>(FrameStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Request>> AsyncFrameStream(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Request>>(AsyncFrameStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Request>> PrepareAsyncFrameStream(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Request>>(PrepareAsyncFrameStreamRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void FrameStream(::grpc::ClientContext* context, ::Response* response, ::grpc::ClientWriteReactor< ::Request>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::Request>* FrameStreamRaw(::grpc::ClientContext* context, ::Response* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::Request>* AsyncFrameStreamRaw(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::Request>* PrepareAsyncFrameStreamRaw(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::Request>> FrameStream(::grpc::ClientContext* context, ::Response* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::Request>>(FrameStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::Request>> AsyncFrameStream(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::Request>>(AsyncFrameStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::Request>> PrepareAsyncFrameStream(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::Request>>(PrepareAsyncFrameStreamRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void FrameStream(::grpc::ClientContext* context, ::Response* response, ::grpc::ClientWriteReactor< ::Request>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::Request>* FrameStreamRaw(::grpc::ClientContext* context, ::Response* response) override;
    ::grpc::ClientAsyncWriter< ::Request>* AsyncFrameStreamRaw(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::Request>* PrepareAsyncFrameStreamRaw(::grpc::ClientContext* context, ::Response* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FrameStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FrameStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::Request>* reader, ::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FrameStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FrameStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FrameStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FrameStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Request>* /*reader*/, ::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFrameStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::Response, ::Request>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FrameStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_FrameStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FrameStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::Request, ::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, ::Response* response) { return this->FrameStream(context, response); }));
    }
    ~WithCallbackMethod_FrameStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FrameStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Request>* /*reader*/, ::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::Request>* FrameStream(
      ::grpc::CallbackServerContext* /*context*/, ::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_FrameStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FrameStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FrameStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FrameStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FrameStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Request>* /*reader*/, ::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FrameStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FrameStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FrameStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FrameStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Request>* /*reader*/, ::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFrameStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FrameStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FrameStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->FrameStream(context, response); }));
    }
    ~WithRawCallbackMethod_FrameStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FrameStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Request>* /*reader*/, ::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* FrameStream(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};


#endif  // GRPC_vision_2eproto__INCLUDED
