# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vision.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cvision.proto\"\x07\n\x05\x45mpty\" \n\rSerialMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0eSerialResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"O\n\rVisionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\"1\n\x0eVisionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07imageid\x18\x02 \x01(\t2=\n\rVisionService\x12,\n\tSendFrame\x12\x0e.VisionRequest\x1a\x0f.VisionResponse2a\n\rSerialService\x12%\n\x0bSendMessage\x12\x0e.SerialMessage\x1a\x06.Empty\x12)\n\x0cSendResponse\x12\x06.Empty\x1a\x0f.SerialResponse0\x01\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=23,
)


_SERIALMESSAGE = _descriptor.Descriptor(
  name='SerialMessage',
  full_name='SerialMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SerialMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=57,
)


_SERIALRESPONSE = _descriptor.Descriptor(
  name='SerialResponse',
  full_name='SerialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SerialResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=91,
)


_VISIONREQUEST = _descriptor.Descriptor(
  name='VisionRequest',
  full_name='VisionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='VisionRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='VisionRequest.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='VisionRequest.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channels', full_name='VisionRequest.channels', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=172,
)


_VISIONRESPONSE = _descriptor.Descriptor(
  name='VisionResponse',
  full_name='VisionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='VisionResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageid', full_name='VisionResponse.imageid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=223,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['SerialMessage'] = _SERIALMESSAGE
DESCRIPTOR.message_types_by_name['SerialResponse'] = _SERIALRESPONSE
DESCRIPTOR.message_types_by_name['VisionRequest'] = _VISIONREQUEST
DESCRIPTOR.message_types_by_name['VisionResponse'] = _VISIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

SerialMessage = _reflection.GeneratedProtocolMessageType('SerialMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERIALMESSAGE,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:SerialMessage)
  })
_sym_db.RegisterMessage(SerialMessage)

SerialResponse = _reflection.GeneratedProtocolMessageType('SerialResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERIALRESPONSE,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:SerialResponse)
  })
_sym_db.RegisterMessage(SerialResponse)

VisionRequest = _reflection.GeneratedProtocolMessageType('VisionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VISIONREQUEST,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:VisionRequest)
  })
_sym_db.RegisterMessage(VisionRequest)

VisionResponse = _reflection.GeneratedProtocolMessageType('VisionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VISIONRESPONSE,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:VisionResponse)
  })
_sym_db.RegisterMessage(VisionResponse)



_VISIONSERVICE = _descriptor.ServiceDescriptor(
  name='VisionService',
  full_name='VisionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=225,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendFrame',
    full_name='VisionService.SendFrame',
    index=0,
    containing_service=None,
    input_type=_VISIONREQUEST,
    output_type=_VISIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISIONSERVICE)

DESCRIPTOR.services_by_name['VisionService'] = _VISIONSERVICE


_SERIALSERVICE = _descriptor.ServiceDescriptor(
  name='SerialService',
  full_name='SerialService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=288,
  serialized_end=385,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='SerialService.SendMessage',
    index=0,
    containing_service=None,
    input_type=_SERIALMESSAGE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendResponse',
    full_name='SerialService.SendResponse',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SERIALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERIALSERVICE)

DESCRIPTOR.services_by_name['SerialService'] = _SERIALSERVICE

# @@protoc_insertion_point(module_scope)
